name: 'Jobs: Workload Validate'

on:
  workflow_call:

permissions:
  contents: read

jobs:
  workload-validate:
    name: Validate, Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Platform Kite
        uses: ./.github/actions/setup-platform-kite
        with:
          azure-login: 'false'

      - name: Install dependencies
        shell: pwsh
        run: |
          Write-Output '➡️ TODO: Install the workload dependencies'

      - name: Validate code
        shell: pwsh
        run: |
          Write-Output '➡️ TODO: validate the workload source'

      - name: Build workload
        shell: pwsh
        run: |
          Write-Output '➡️ TODO: Build the workload'

      - name: Run tests
        shell: pwsh
        run: |
          Write-Output '➡️ TODO: Run the workload tests'
